config/routes.rb
Rails.application.routes.draw do
  
  get 'downpanel/chekoutinf'

  get 'downpanel/payinf'

  get 'downpanel/shipinf'

  get 'downpanel/faq'

   get 'admin' => 'admin#index'
      controller :sessions do
          get 'login' => :new
          post 'login' => :create
          delete 'logout' => :destroy
      end
  
  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items do
    patch 'minus_quantity', on: :member
  end

  resources :carts

  get 'store/index'
  
  resources :products do
          get :who_bought, on: :member
     end

  resources :products
  
  root to: 'store#index', as: 'store' #задана главная страница as: 'store' создает store_path

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html> <%# Это файл макета-шаблона для всех веб-страниц%>
<html>
  
  
  
<head>
  
  <title>MyGift.com</title> <%# заголовок страницы%>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>


  <body class='<%= controller.controller_name %>'> <%#На каждой странице будет свой стиль css по названию контроллера%>
  

             <div id="banner"> <%# в id подставляются классы из css файла%>
               <%= image_tag("logo.png") %> <%# ссылка на URL изображения%>
               <%= @page_title || "MyGift" %> <%#название страницы%>
               
                <div id="search">
               <%= render :partial => "products/search" %>
               </div>
             </div>
    

             <div id="columns">
               
                <div id="side">
                  
                  <div id="cart">
                      <% if @cart %>
                          <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
                              <%= render @cart %>
                          <% end %>
                    
                      <% end %>
                  </div>
                  
               <% if session[:user_id] %>
                   <p><%= "You signed as: Admin"%></p>
                  <ul>
                       <li><%= link_to 'Orders', orders_path %></li>
                       <li><%= link_to 'Products', products_path %></li>
                       <li><%= link_to 'Users', users_path %></li>
                   </ul>
                  <%= button_to 'Logout', logout_path, method: :delete %>
               <% end %>
                  
                   <p> <%= "The time is: #{@time}"%> </p>  
                </div>
               
                <div id="main">
                 <%= yield %> <%#вызов кода erb и вывод приложения%>
                </div>
               
            </div>
    
  
     
    <div id="footer">
      <%= link_to 'Как оформить заказ' , downpanel_chekoutinf_path %>
      <%= link_to 'Оплата заказа' , downpanel_payinf_path %>
      <%= link_to 'Доставка' , downpanel_shipinf_path %>
      <%= link_to 'FAQ' , downpanel_faq_path %>
    </div>
    
  
  
   </body>
    
   
</html>